/*
 * Copyright (c) 2023 Óscar Otero
 * All rights reserved.
 */

package org.js.vento.webstormvento

import com.intellij.lexer.FlexAdapter
import org.js.vento.webstormvento.VentoLexer

/**
 * Adapts the Flex-based VentoLexer for use in the IntelliJ Platform.
 * It assumes there's a generated Java class named VentoLexer
 * from a corresponding .flex file (VentoLexer.flex).
 */
class VentoLexerAdapter : FlexAdapter(VentoLexer(null))
//Explanation:
//• VentoLexer is usually a Java class generated by running the IntelliJ JFlex tool on your VentoLexer.flex file.
//• FlexAdapter wraps this generated lexer class so the IntelliJ Platform (WebStorm) can integrate it as your custom language lexer.
//• Your parser definition (VentoParserDefinition) will call VentoLexerAdapter when it needs to tokenize Vento files.